services:
  auth-db:
    container_name: auth-db
    image: postgres:12.5-alpine
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - auth
    ports:
      - "5432:5432"

  auth-api:
    build: .
    container_name: auth-api
    depends_on:
      - auth-db
    networks:
      - auth
    environment:
      - JWT_SECRET_KEY=Y3Vyc28t...
      - DB_HOST=auth-db
      - DB_NAME=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    ports:
      - "8080:8080"

networks:
  auth:
    driver: bridge
